import os
import aiohttp
import warnings
import litellm
from typing import List, Dict, Any, Optional , Union

# Package Imports
from .base import BaseModel
from .types import CompletionResponse
from ..errors import ModelAccessError, NotAVisionModel, MissingEnvironmentVariables
from ..constants.messages import Messages
from ..constants.prompts import Prompts
from ..processor.image import encode_image_to_base64

DEFAULT_SYSTEM_PROMPT = Prompts.DEFAULT_SYSTEM_PROMPT


class litellmmodel(BaseModel):
    ## setting the default system prompt
    _system_prompt = DEFAULT_SYSTEM_PROMPT

    def __init__(
        self,
        model: Optional[str] = None,
        **kwargs,
    ):
        """
        Initializes the Litellm model interface.
        :param model: The model to use for generating completions, defaults to "gpt-4o-mini". Refer: https://docs.litellm.ai/docs/providers
        :type model: str, optional
        
        :param kwargs: Additional keyword arguments to pass to self.completion -> litellm.completion. Refer: https://docs.litellm.ai/docs/providers and https://docs.litellm.ai/docs/completion/input
        """
        super().__init__(model=model, **kwargs)

        ## calling custom methods to validate the environment and model
        self.validate_environment()
        self.validate_model()
        self.validate_access()

    @property
    def system_prompt(self) -> str:
        '''Returns the system prompt for the model.'''
        return self._system_prompt
    
    @system_prompt.setter
    def system_prompt(self, prompt: str) -> None:
        '''
        Sets/overrides the system prompt for the model.
        Will raise a friendly warning to notify the user. 
        '''
        warnings.warn(f"{Messages.CUSTOM_SYSTEM_PROMPT_WARNING}. Default prompt for zerox is:\n {DEFAULT_SYSTEM_PROMPT}")
        self._system_prompt = prompt

    ## custom method on top of BaseModel
    def validate_environment(self) -> None:
        """Validates the environment variables required for the model."""
        env_config = litellm.validate_environment(model=self.model)

        if not env_config["keys_in_environment"]:
            raise MissingEnvironmentVariables(extra_info=env_config)
        
    def validate_model(self) -> None:
        '''Validates the model to ensure it is a vision model.'''
        if not litellm.supports_vision(model=self.model):
            raise NotAVisionModel(extra_info={"model": self.model})
        
    def validate_access(self) -> None:
        """Validates access to the model -> if environment variables are set correctly with correct values."""
        if not litellm.check_valid_key(model=self.model,api_key=None):
            raise ModelAccessError(extra_info={"model": self.model})
        

    async def cleaning_postprocessing(self, content: str , postprocessing_prompt: str) -> str:
        """Post-processes the completion response to validate latex syntax.

        :param content: The completion response from the model.
        :type content: str

        :return: The post-processed markdown content.
        :rtype: str
        """
        messages: List[Dict[str, Any]] = [
            {
                "role": "system",
                "content": f""" Your are a postprocessing system that needs to reproduce the input with considering the following instruction. 
                        Return the output only with no explaination sentences.\n
                        The Instructions:
                        {postprocessing_prompt}""",
            },
        ]


        messages.extend([
            {
                "role": "user",
                "content": content
            }
        ])




        response = await litellm.acompletion(model=self.model, messages=messages, **self.kwargs)
        ## completion response

        return response["choices"][0]["message"]["content"]
    

    async def completion(
        self,
        image_paths: Union[str, List[str]],
        maintain_format: bool,
        prior_page: str,
        prior_page_path: str,
        fewshot_examples_paths: Any = None
    ) -> CompletionResponse:
        """LitellM completion for image to markdown conversion.

        :param image_path: Path to the image file.
        :type image_path: str
        :param maintain_format: Whether to maintain the format from the previous page.
        :type maintain_format: bool
        :param prior_page: The markdown content of the previous page.
        :type prior_page: str

        :return: The markdown content generated by the model.
        """
        messages = await self._prepare_messages(
            image_paths=image_paths,
            maintain_format=maintain_format,
            prior_page=prior_page,
            prior_page_path=prior_page_path,
            fewshot_examples_paths= fewshot_examples_paths
        )

        try:
            response = await litellm.acompletion(model=self.model, messages=messages, **self.kwargs)
            ## completion response
            response = CompletionResponse(
                    content=response["choices"][0]["message"]["content"],
                    input_tokens=response["usage"]["prompt_tokens"],
                    output_tokens=response["usage"]["completion_tokens"],
                )
            return response
        
        except Exception as err:
            raise Exception(Messages.COMPLETION_ERROR.format(err))


    # # post-process the completion response using llm
    # async def post_process_completion(self, completion: CompletionResponse , image_path) -> str:
    #     """Post-processes the completion response to remove unwanted tokens.

    #     :param completion: The completion response from the model.
    #     :type completion: CompletionResponse

    #     :return: The post-processed markdown content.
    #     :rtype: str
    #     """

    #     messages: List[Dict[str, Any]] = [
    #         {
    #             "role": "system",
    #             "content": "Your are a latex validator, you will be given images and latex generated by you, you have to validate the latex generated by you with the images given to you",
    #         },
    #     ]
    #     base64_image = await encode_image_to_base64(image_path)


    #     messages.append({
    #                     "role": "user",
    #                     "content":  [
    #                         {
    #                             "image": {"url": f"data:image/png;base64,{base64_image}"},
    #                             "generated_latex": completion["choices"][0]["message"]["content"]
    #                         },
    #                     ],
    #                 })
        
    #     return messages




    async def _prepare_messages(
        self,
        image_paths: Union[str, List[str]],
        maintain_format: bool,
        prior_page: str,
        prior_page_path: str,
        fewshot_examples_paths: Any = None
    ) -> List[Dict[str, Any]]:
        """Prepares the messages to send to the LiteLLM Completion API.

        :param image_path: Path to the image file.
        :type image_path: str
        :param maintain_format: Whether to maintain the format from the previous page.
        :type maintain_format: bool
        :param prior_page: The markdown content of the previous page.
        :type prior_page: str
        """
        # Default system message
        messages: List[Dict[str, Any]] = [
            {
                "role": "system",
                "content": self._system_prompt,
            },
        ]

        # If content has already been generated, add it to context.
        # This helps maintain the same format across pages.
        if prior_page_path:
            base64_image = await encode_image_to_base64(prior_page_path)
        else:
            base64_image = None

        if maintain_format and prior_page:
             messages.extend([
                    {
                        "role": "user",
                        "content":  f""" The prior pages' Latex of all the document is: {prior_page} and the prior page image is """        
                    },
                    {
                        "role": "user",
                        "content":  [
                            {
                                "type": "image_url",
                                "image_url": {"url": f"data:image/png;base64,{base64_image}"},
                            },
                        ],
                    },

                     {
                        "role": "user",
                        "content":  f"""Now generating the full new latex of all the document after the next image"""        
                    },
            ])



        if fewshot_examples_paths:
                                
                for fs_example in fewshot_examples_paths:
                    
                    
                    example_img_path, example_groundtruth_path = fs_example
                    
                    assert os.path.exists(example_img_path), f"Fewshot example image `{example_img_path}` was not found"
                    assert os.path.exists(example_groundtruth_path), f"Fewshot example ground truth file `{example_groundtruth_path}` was not found"
                    
                    base64_image = await encode_image_to_base64(example_img_path)
                    # TODO: add a utility common file with ut.ReadFile support
                    example_groundtruth_latex = '\n'.join(open(example_groundtruth_path, "r") .readlines())
                    
                    messages.extend([
                        {
                            "role": "user",
                            "content":  [
                                {
                                    "type": "image_url",
                                    "image_url": {"url": f"data:image/png;base64,{base64_image}"},
                                },
                            ],
                        }, 
                        {
                            "role": "assistant",
                            "content": example_groundtruth_latex
                        }
                    ])

                if isinstance(image_paths, str):
                    image_paths = [image_paths]
                print(image_paths)
                content_images_encoded = [  ]
                for img_path in image_paths:
                    base64_image = await encode_image_to_base64(img_path)
                    content_images_encoded.append(
                        {
                            "type": "image_url",
                            "image_url": {"url": f"data:image/png;base64,{base64_image}"},
                        }
                    )
                    
                # Add Image to request
                messages.append(
                    {
                        "role": "user",
                        "content": content_images_encoded
                    }
                )

        return messages
